export const listings = [
    {
      id: 1,
      image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
      price: "129",
      title: "Maison de vacances d'Agdal",
      description: "Plongez au cœur d'Agdal Rabat dans notre suite signature, une expérience inégalée. Profitez d'un spacieux hôtel contemporain, doté d'un lit king size, d'une connexion Wi-Fi, et d'une télévision. Réservez dès maintenant pour vivre pleinement le charme central de Rabat.",
      location: "Kärvingeborn, Hällefors",
      rating: 4.9,
      reviews: 37,
      info:{
        surface: 120,
        typeChombre:"Chambre Double",
        Capacité:1,
        chambre:3,
        piscine:true, 
        Bains:true, 
        wifi:false,
      }
    },
    {
      id: 2,
      image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
      price: "117",
      title: "Maison de vacances d'Agdal",
      description: "Plongez au cœur d'Agdal Rabat dans notre suite signature, une expérience inégalée. Profitez d'un spacieux hôtel contemporain, doté d'un lit king size, d'une connexion Wi-Fi, et d'une télévision. Réservez dès maintenant pour vivre pleinement le charme central de Rabat.",
      location: "Samsø Municipality, Samsø",
      rating: 4.4,
      reviews: 7,
      info:{
        surface: 120,
        typeChombre:"Chambre Double",
        Capacité:1,
        chambre:3,
        piscine:true, 
        Bains:true, 
        wifi:false,
      }
    },
    {
      id: 3,
      image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
      price: "189",
      title: "Maison de vacances • 6 pers. • 4 chambres",
      description: "Charmante maison de vacances entièrement équipée",
      location: "Sylt, Schleswig-Holstein",
      rating: 5.0,
      reviews: 17,
    },
    {
      id: 4,
      image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
      price: "155",
      title: "Péniche • 4 pers. • 2 chambres",
      description: "Bateau avec barbecue et terrasse | Vue sur le port",
      location: "Fehmarn, Arrondissement du Holstein",
      rating: 4.5,
      reviews: 4,
    },
    {
        id: 2,
        image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
        price: "117",
        title: "Maison de vacances • 2 pers. • 2 chambres",
        description: "Maison de vacances avec sauna | Vue sur la mer",
        location: "Samsø Municipality, Samsø",
        rating: 4.4,
        reviews: 7,
      },
      {
        id: 2,
        image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
        price: "117",
        title: "Maison de vacances • 2 pers. • 2 chambres",
        description: "Maison de vacances avec sauna | Vue sur la mer",
        location: "Samsø Municipality, Samsø",
        rating: 4.4,
        reviews: 7,
      },
      {
        id: 2,
        image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
        price: "117",
        title: "Maison de vacances • 2 pers. • 2 chambres",
        description: "Maison de vacances avec sauna | Vue sur la mer",
        location: "Samsø Municipality, Samsø",
        rating: 4.4,
        reviews: 7,
      },
      {
        id: 2,
        image: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9taWNpbGV8ZW58MHx8MHx8fDA%3D",
        price: "117",
        title: "Maison de vacances • 2 pers. • 2 chambres",
        description: "Maison de vacances avec sauna | Vue sur la mer",
        location: "Samsø Municipality, Samsø",
        rating: 4.4,
        reviews: 7,
      },
  ]